### ISSUE TITLE
Master does not authenticate

### ISSUE THREAD

**Issue by lordfolken** [3cst4sy/vereinsflieger-login#2]
I'm unable to get the current master branch to work. There seems to be no error, even with debug settings. Is there anyone with better experience?

The CID is just the number, no CID infront correct?

**Comment by silviokennecke** [comment]
I didn't got this plugin to work for my purposes, too. Now I developed a new one. You can find it under https://github.com/Diginize/wp-vereinsflieger

I'm currently waiting for the review. Thereafter you can download and install it also directly from the wordpress plugins page. If you don't want to wait you can simply download and install the zip file, provided in the release [v1.0.0](https://github.com/Diginize/wp-vereinsflieger/releases/tag/1.0.0)

**Comment by silviokennecke** [comment]
Hi @lordfolken,
nearly forgot this ticket.
You can now also install my Plugin directly from the Wordpress Plugin Directory. Simply search for “Vereinsflieger” (there is just one plugin).
If it works for you I’d be happy if you leave a review at https://wordpress.org/plugins/wp-vereinsflieger/
Thanks.
